host ?= 0.0.0.0
port ?= 8000
lint-dir ?= .

.PHONY: help
help: ## Generates a help README
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: lint
app_lint: ## lint and format code with Ruff
	ruff check $(lint-dir) --fix ; ruff format $(lint-dir)

.PHONY: test
app_test: ## run tests with Pytest
	pytest .

.PHONY: serve
app_serve: ## run app with Uvicorn
	uvicorn app:app --host $(host) --port $(port) --reload

.PHONY: docker_build
docker_build: ## build app image (use with sudo)
	docker build . --tag {{service_name}}

.PHONY: docker_run
docker_run: ## run app container (use with sudo)
	docker run -d -p $(port):$(port) --name {{service_name}} {{service_name}}

.PHONY: docker_stop
docker_stop: ## stop docker container (use with sudo)
	docker stop {{service_name}}

.PHONY: env_create
env_create: ## create env
	pyenv virtualenv {{service_name}}-{{python_version}}

.PHONY: pip_upgrade
pip_upgrade:  ## upgrade pip
	python -m pip install --upgrade pip

.PHONY: pip_install
pip_install:  ## install dependencies
	pip install -r requirements.txt